
public class NewJFrame extends javax.swing.JFrame {
    String contents;
    String orderStr;
    int length; 
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrompt = new javax.swing.JLabel();
        chkCoffee = new javax.swing.JCheckBox();
        chkCola = new javax.swing.JCheckBox();
        chkMilk = new javax.swing.JCheckBox();
        chkWater = new javax.swing.JCheckBox();
        chkTea = new javax.swing.JCheckBox();
        btnOrder = new javax.swing.JButton();
        lblOrder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrompt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrompt.setText("What would you like to drink?");

        chkCoffee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chkCoffee.setText("Coffee");
        chkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCoffeeActionPerformed(evt);
            }
        });

        chkCola.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chkCola.setText("Cola");
        chkCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkColaActionPerformed(evt);
            }
        });

        chkMilk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chkMilk.setText("Milk");
        chkMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMilkActionPerformed(evt);
            }
        });

        chkWater.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chkWater.setText("Water");
        chkWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWaterActionPerformed(evt);
            }
        });

        chkTea.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chkTea.setText("Tea");
        chkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTeaActionPerformed(evt);
            }
        });

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        lblOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCoffee)
                        .addGap(18, 18, 18)
                        .addComponent(chkCola)
                        .addGap(19, 19, 19)
                        .addComponent(chkMilk)
                        .addGap(18, 18, 18)
                        .addComponent(chkWater)
                        .addGap(27, 27, 27)
                        .addComponent(chkTea)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btnOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrompt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCoffee)
                    .addComponent(chkCola)
                    .addComponent(chkMilk)
                    .addComponent(chkWater)
                    .addComponent(chkTea))
                .addGap(18, 18, 18)
                .addComponent(btnOrder)
                .addGap(18, 18, 18)
                .addComponent(lblOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        String orderStr;
        
        orderStr = "You chose ";
        if (chkCoffee.isSelected())
            orderStr += "coffee ";
        if (chkCola.isSelected())
            orderStr += "cola ";
        if (chkMilk.isSelected())
            orderStr += "milk ";
        if (chkWater.isSelected())
            orderStr += "water ";
        if (chkTea.isSelected())
            orderStr += "tea ";
        
        lblOrder.setText(orderStr);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void chkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCoffeeActionPerformed
        contents = buildOrder(contents);
        lblOrder.setText(orderStr);
    }//GEN-LAST:event_chkCoffeeActionPerformed

    private void chkColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkColaActionPerformed
        contents = buildOrder(contents);
        lblOrder.setText(orderStr);
    }//GEN-LAST:event_chkColaActionPerformed

    private void chkMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMilkActionPerformed
        contents = buildOrder(contents);
        lblOrder.setText(orderStr);
    }//GEN-LAST:event_chkMilkActionPerformed

    private void chkWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWaterActionPerformed
        contents = buildOrder(contents);
        lblOrder.setText(orderStr);
    }//GEN-LAST:event_chkWaterActionPerformed

    private void chkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTeaActionPerformed
        contents = buildOrder(contents);
        lblOrder.setText(orderStr);
    }//GEN-LAST:event_chkTeaActionPerformed
       private String buildOrder(String orderStr)
    {
        orderStr = "You chose";
        length = orderStr.length();
        if(chkCoffee.isSelected())
        {
            orderStr += " cofee";
        }
        if(chkCola.isSelected())
        {
            if(length == orderStr.length() && orderStr.contains("You chose"))
                orderStr += " cola";
            else
                orderStr += " and cola";  
        }
        if(chkMilk.isSelected())
        {
            if(length == orderStr.length() && orderStr.contains("You chose"))
                orderStr += " milk";
            else
                orderStr += " and milk";  
        }
        if(chkWater.isSelected())
        {
            if(length == orderStr.length() && orderStr.contains("You chose"))
                orderStr += " water";
            else
                orderStr += " and water";  
        }
        if(chkTea.isSelected())
        {
            if(length == orderStr.length() && orderStr.contains("You chose"))
                orderStr += " tea";
            else
                orderStr += " and tea";  
        }
        if(!chkCoffee.isSelected() && !chkCola.isSelected() && 
             !chkMilk.isSelected() && !chkWater.isSelected() && 
             !chkTea.isSelected())
            orderStr = "";
        lblOrder.setText(orderStr);
        
        return orderStr;
    }                                    

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JCheckBox chkCoffee;
    private javax.swing.JCheckBox chkCola;
    private javax.swing.JCheckBox chkMilk;
    private javax.swing.JCheckBox chkTea;
    private javax.swing.JCheckBox chkWater;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblPrompt;
    // End of variables declaration//GEN-END:variables
}
