/*
Author: Oberon Ilano
Description:        
 */
package ResortPriceEstimator;

/**
 *
 * @author CIS Student
 */
public class Estimator extends javax.swing.JFrame {
    final int BASE_PRICE = 200;
    final int WEEKEND_PREMIUM = 100;
    final int BREAKFAST_PREMIUM = 20;
    final int GOLF_PREMIUM = 75;
    int totalPrice = BASE_PRICE;
            
    public Estimator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        lblChkOption = new javax.swing.JLabel();
        chkPremium = new javax.swing.JCheckBox();
        chkBreakfast = new javax.swing.JCheckBox();
        chkGolf = new javax.swing.JCheckBox();
        lblPriceMessage = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Resort Price Calculator");

        lblSubTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubTitle.setText("Base price for a room is $200");

        lblChkOption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChkOption.setText("Check the options you want");

        chkPremium.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkPremium.setText("Weekend Premium $100");
        chkPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPremiumActionPerformed(evt);
            }
        });

        chkBreakfast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkBreakfast.setText("Breakfast $20");
        chkBreakfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBreakfastActionPerformed(evt);
            }
        });

        chkGolf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkGolf.setText("Golf $75");
        chkGolf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGolfActionPerformed(evt);
            }
        });

        lblPriceMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPriceMessage.setText("The price for your stay is");

        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrice.setText("$200");
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkGolf)
                        .addGap(27, 27, 27)
                        .addComponent(lblPriceMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkPremium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkBreakfast)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblChkOption))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTitle)
                            .addGap(153, 153, 153))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(115, 115, 115)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChkOption)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPremium)
                    .addComponent(chkBreakfast))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGolf)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriceMessage))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBreakfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBreakfastActionPerformed
        if (chkBreakfast.isSelected())
        {
            totalPrice += BREAKFAST_PREMIUM;
        }
        else 
        {
            totalPrice -= BREAKFAST_PREMIUM;
        }
        txtPrice.setText("$" + Integer.toString(totalPrice));
    }//GEN-LAST:event_chkBreakfastActionPerformed

    private void chkGolfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGolfActionPerformed
        if (chkGolf.isSelected())
        {
            totalPrice += GOLF_PREMIUM;
        }
        else 
        {
            totalPrice -= GOLF_PREMIUM;
        }
        txtPrice.setText("$" + Integer.toString(totalPrice));
    }//GEN-LAST:event_chkGolfActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void chkPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPremiumActionPerformed
        if (chkPremium.isSelected())
        {
            totalPrice += WEEKEND_PREMIUM;
        }
        else 
        {
            totalPrice -= WEEKEND_PREMIUM;
        }
        txtPrice.setText("$" + Integer.toString(totalPrice));
    }//GEN-LAST:event_chkPremiumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estimator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBreakfast;
    private javax.swing.JCheckBox chkGolf;
    private javax.swing.JCheckBox chkPremium;
    private javax.swing.JLabel lblChkOption;
    private javax.swing.JLabel lblPriceMessage;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
